server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      rule: random

    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          # If using Eureka, this should be: uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/user-service/**

        - id: vehicle-service
          uri: http://localhost:8082
          predicates:
            - Path=/vehicle-service/**

        - id: parking-service
          uri: http://localhost:8083
          predicates:
            - Path=/parking-service/**

        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/payment-service/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/