spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_service_db?createDatabaseIfNotExist=true
    username: root
    password: Ijse@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

  config:
    import: optional:configserver:http://localhost:8888/

server:
  port: 8081


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: "2D4A614E645267556B58703273357638792F423F4428472B4B6250655368566DF423F4428472B4B6250655368566D"
